external_dependencies:
  - name: my_test_service
    host: 127.0.0.1:8001
    grpc:
      - /Users/usanin/Documents/go_projects/test_cmd/pb/service_b.proto
      - /Users/usanin/Documents/go_projects/test_cmd/pb/service_c.proto